language: scala
matrix:
  include:
  - jdk: oraclejdk8
    scala: 2.12.4
    env: COMMAND=validate

script:
  - sbt -J-Xmx1024m ++$TRAVIS_SCALA_VERSION $COMMAND

env:
  global:
  - secure: BUwoUugJ5WNgQcetu/9tRP8G3unhmUBSnCj3cGVhRkgWDPz1cIgtKukp5D6Bq97PRMGK1co/kNOvdVVXLN7wPG4PowmaXnmd7xuNvpRLkDM0sj7fBk92ocYFgLVq30bbY7budx85isgx3z1hzQXVbbLSmdbP7WGqCccdwmQOdnkXobSj7l8SHzsH1vT/Bh3IQ+Yq9lmJbURGRRj9kjosQfSneBVltxSS5NWOf1oPZeRD4DtHmX+6CJxAln9RZnwk2eutsJrSwrmcZvA6+1z4SQArncj+9TZTG7lcjqw99v6VBT9eEp92ifN3UeJxBu8h1/Cl6yzLuIyPtgzXTNvehV6QuefdpcoFYTM0jXsxFk8sOpmG5Upw/2Wc2gpuplezOzpDs3JP/VVW78rlzJ0xThr8j8pBEB/2Dx4n/Wu8T034FIptYhkqMhc09OfXAQ1zz50eBe/zCJZzggoKJcSfJq3DM3+C60g3Z0MnzxogAUMu3pvE3bayOELNWJyqHMC2cS12izJr5avjgpY7dYFEK7tfdRB/QBrbX5Ul3KJUAl47houLMptBTYr3gtIMLQZbfMf3ngnf72Qbs/8NS4Hm8a5jqyrlDKOGmPoHjheuKjQH5XT5IWzYFKeMdTAF8ldMCN5yW6Nk1hEGbKOyCAdzAHWmF0GFKNBaz+JJI+UjEEM=
  - secure: TvrGFxVPdI8Qhctpn8tm/cM/O+WvjfrhT4vKTNmJgsXBt2fGlXe7Uaukf19GShis+i3Ja87+C3HU1vovY09KJMWDir491PXWlzxvtj1yd5KtlNW7akScPmWH2w6mUTEHzltKa2l+GxH1Wc3bD9XK9+ilXbx9TpafzWqoq12lgH7GogrnwfPzJihLbY0i7Bcyo/c9no1eT/jyy0cGXRgopWGtnzxrVnTbwS30Tm8iNihWYu7ufBWHjtIDABIfCQRZDj1DmoSa5EetmOvs/ey0+NMQy4GXpzKAZkBQhbGe5QBSdECCh4KCgYuzEgQ2aj3bdY8115ZHtB/f/l77UhYrBTTSgUKjYORMkPjc/qE5KTLSokmHIjQnWvt+QWwfyDpTdCvw8/pe/5uAyf4eBXSQGebJ7gJsKNnsJ14WKMQf9UyKhTwyEAfSEAAMPwhSFNKWOGsZkr1odl+1UHwCAPXYUBfeC+/BtfuoHg+Jmluyd/1hXzyJ4/l4KxBPPdkTrHoNQHAmdPBIX5VGuRtjZrV7EAbkJ99SH0+gNjz49yWgrfcgFuM5YUEqHttr41pdiS5pExbOio3vUtU7G65ZQZ+Kx28mUUG9IEQYR0Rv9tapB98aplqxLx6HMUzIA5NLqfTMA46tSpnn6Rz1BM28XzbklvOyOMkAt4T2diagf6RKn5Y=
  - secure: mZZ3e266m+NrDx/a8Qiiefti+8rHaJDsnHyr5DDMPdbOZPArQ3pYpavZkEMoKZFwlkSBaV8Ez8j6UsmxKf8LSWKk41/QsmvbPzjgk5CseQMvu5QAbW8klvYzvUrquExpZirhBP+iA8gVe/FXJd7HbK/fYSSAZsxQjyS1C45CwegoRo9cf1Bez9jfkCvZlWSHsYKeD0xAJnfTzQlyPqmbv3pF7JODlGSNXHP+zW6hBVZ4OaLhkiCBz+7C2l/daN8c7VT/DKAtaQ3kHds60f5RvWdmnLbGBdQd8IlnnDfPIRFZqruWdARdu6wcsh8yQfQN5LdYXR7GcLVks4MZxCdaY0JA58RJkm+mq8k2V4K4EHZG0cXaXnrd06w4pheDgQfCVmxuDcxdq4QQeNq7Y6DgOmdOkFB1ngobtr9BqWVUb3sBF5Xy9nq8Xl5lRg0JMVctHm9zeW93+JWp6ZR8PTU6LOfbvF5et+o+vySeJ6EaSrKtJ1WkGPmRFUZGNiJajva5q687yd3hB7ka0r8eZzQAc9N7VNlYoTISCdPuY39FzOfLScdw77rHyTAqNMQQaulwMhpWH6s2ofdp3KMvJezQ0qYJx1TpO1ZH5EZI7zkS4H4mDCRfy+n06qFk1muyvx5G6hVZi7ZQHFU1ao/+by1XItRsyvjYsYWffG9VZ++0S0A=

before_deploy:
  - openssl aes-256-cbc -K $encrypted_ef7a89177743_key -iv $encrypted_ef7a89177743_iv
    -in project/.gnupg/sec.asc.enc -out project/.gnupg/sec.asc -d

deploy:
  - provider: script
    script: sbt publishViaTravis
    skip_cleanup: true
    on:
      tags: true
      condition: $TRAVIS_PULL_REQUEST = false
  - provider: script
    script: sbt publishViaTravis
    skip_cleanup: true
    on:
      branch: snapshot
      condition: $TRAVIS_PULL_REQUEST = false
